data:
  additive_gaussian_noise: true
  augmentation: true
  augmentation_kwargs:
    rotating: true
    subsampling: true
  augmentation_mode: 1
  autoscale: false
  epsilon_scaling: 1.0
  input_channels:
  - terrain
  - ux
  - uy
  - uz
  input_mode: 1
  input_smoothing: false
  input_smoothing_interpolation: true
  input_smoothing_interpolation_linear: true
  label_channels:
  - ux
  - uy
  - uz
  max_fraction_of_sparse_data: 0.1
  max_gaussian_noise_std: 0.0
  max_normalized_bias_scale: 0.0
  max_normalized_turb_scale: 0.0
  min_fraction_of_sparse_data: 0.001
  n_turb_fields: 0
  nut_scaling: 1.0
  only_z_velocity_bias: false
  p_scaling: 1.0
  stride_hor: 1
  stride_vert: 1
  terrain_scaling: 1.0
  testset_name: data/test_resampled.hdf5
  trainset_name: data/train.hdf5
  trajectory_length_short_focus: false
  trajectory_max_iter: 50
  trajectory_max_length: 300
  trajectory_max_segment_length: 20
  trajectory_min_length: 30
  trajectory_min_segment_length: 5
  trajectory_start_weighting_mode: 0
  trajectory_step_size: 1.0
  turb_scaling: 1.0
  ux_scaling: 1.0
  uy_scaling: 1.0
  uz_scaling: 1.0
  validationset_name: data/validation_resampled.hdf5
loss:
  DivergenceFreeLoss_kwargs:
    exclude_terrain: true
    loss_factor_init: -1.5
    loss_type: L1
  GaussianLogLikelihoodLoss_kwargs:
    exclude_terrain: true
    loss_factor_init: 0.0
    uncertainty_loss_eps: 1e-8
  KLDivLoss_kwargs:
    loss_factor_init: 0.0
  L1Loss_kwargs:
    exclude_terrain: true
    loss_factor_init: -0.5
  L2Loss_kwargs:
    exclude_terrain: true
    loss_factor_init: -0.5
    p: 2
  L4Loss_kwargs:
    exclude_terrain: true
    loss_factor_init: 1.5
  LPLoss_kwargs:
    exclude_terrain: true
    loss_factor_init: 0.0
    p: 1.7
  ScaledLoss_kwargs:
    exclude_terrain: true
    loss_factor_init: 0.0
    max_scale: 4
    no_scaling: true
    norm_threshold: 0.5
  VelocityGradientLoss_kwargs:
    exclude_terrain: true
    loss_factor_init: -1.5
    loss_type: L1
  auto_channel_scaling: true
  eps_scaling: 1
  eps_scheduling_kwargs:
    gamma: 0.998
    step_size: 10
  eps_scheduling_mode: decay
  learn_scaling: true
  log_loss_components: true
  loss_components:
  - L2Loss
  loss_weighting_clamp: true
  loss_weighting_fn: 0
model:
  model_args:
    activation_args:
      negative_slope: 0.1
    activation_type: LeakyReLU
    align_corners: false
    channel_multiplier: 2
    fc_scaling: 8
    filter_kernel_size: 3
    grid_size:
    - 16.64444351196289
    - 16.64444351196289
    - 11.578947067260742
    interpolation_mode: nearest
    logvar_scaling: 10
    n_downsample_layers: 4
    n_epochs: 200
    n_first_conv_channels: 16
    n_stacked: 3
    n_x: 64
    n_y: 64
    n_z: 64
    pass_full_output: false
    pooling_method: striding
    potential_flow: false
    predict_uncertainty: false
    skipping: true
    submodel_terrain_mask: false
    submodel_type: ModelEDNN3D
    uncertainty_train_mode: alternating
    use_epsilon: false
    use_fc_layers: false
    use_mapping_layer: false
    use_nut: false
    use_pressure: false
    use_sparse_convolution: false
    use_sparse_mask: false
    use_terrain_mask: true
    use_turbulence: false
    use_uz_in: true
    vae: false
    verbose: true
  model_type: ModelEDNN3D
  name_prefix: test_model
run:
  batchsize: 56
  compute_validation_loss: true
  compute_validation_loss_every_n_epochs: 10
  custom_init: false
  evaluate_testset: false
  learning_rate_decay: 0.25
  learning_rate_decay_step_size: 750
  minibatch_epoch_loss: true
  n_epochs: 200
  num_workers: 8
  optimizer_kwargs:
    lr: 0.0001
  optimizer_type: adam
  plot_every_n_batches: 5
  save_metadata: true
  save_model: true
  save_model_every_n_epoch: 25
  save_params_hist_every_n_epoch: 100
  warm_start: false
